name: init-env-linux
description: Prepare Linux environment for tauri
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libgtk-3-dev webkit2gtk-4.1 libayatana-appindicator3-dev