name: Feature Request
description: Suggest a new feature or enhancement
labels: [feature]
body:
  - type: input
    id: title
    attributes:
      label: Feature title
      description: Short, clear name for the feature
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve? Why is it important?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see.
      placeholder: |
        Example: Add a toggle for dark mode in the settings menu.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (Optional)
      description: What other solutions have you thought about or tried?
      placeholder: |
        Example: Use system theme, third-party extensions, etc.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context (Optional)
      description: Add any other context, mockups, screenshots, or examples here.
    validations:
      required: false