name: Lint TS

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    paths:
      - ".github/workflows/lint-ts.yml"
      - "apps/**"
      - "packages/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/init-env-node
      - run: pnpm type-check

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/init-env-node
      - run: pnpm format-check
