# https://github.com/actions/labeler#create-workflow

name: Label PRs
on:
  pull_request_target:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: "popcorntime/popcorntime"
      - uses: actions/labeler@v6
        with:
          configuration-path: ".github/pr-labeler.yaml"
