name: Test TS

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    paths:
      - ".github/workflows/test-ts.yaml"
      - "apps/**"
      - "packages/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/init-env-node
      - run: pnpm test
